services:
  db:
    image: mysql:8.0
    container_name: scut_mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./db/docker-init.sql:/docker-entrypoint-initdb.d/2_init_users.sql:ro
      - ./db/init_admin.sh:/docker-entrypoint-initdb.d/3_init_admin.sh:ro
      - ./db/seed_products.sql:/docker-entrypoint-initdb.d/4_seed_products.sql:ro
    ports:
      - "3307:3306" # changed host port to 3307 because host 3306 is in use
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: scut_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: scut_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: scut_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  app:
    build: ./backend
    container_name: scut_app
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - PAYMENT_MOCK=${PAYMENT_MOCK}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - EMAIL_ACTIVATION_ENABLED=true
      - FRONTEND_BASE=http://localhost:3000
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG

    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
      - mailhog
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=
    container_name: scut_frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db_data:
