spring:
  datasource:
    url: jdbc:h2:mem:scut_e2e;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/h2-init.sql
      continue-on-error: true
jwt:
  secret: replace_with_a_very_long_test_secret_of_at_least_32_bytes_1234567890

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.scutshop: DEBUG
